/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BottomBar: typeof import('./src/components/layout/BottomBar.vue')['default']
    Common: typeof import('./src/components/common/Common.vue')['default']
    CrontabsForm: typeof import('./src/components/crontabs/CrontabsForm.vue')['default']
    CrontabsSearch: typeof import('./src/components/crontabs/CrontabsSearch.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    Layout: typeof import('./src/components/layout/Layout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideNavBar: typeof import('./src/components/layout/SideNavBar.vue')['default']
    TopBar: typeof import('./src/components/layout/TopBar.vue')['default']
  }
}
